name: Build and Deploy to Function App
on:
  push:
    branches:
    - main
env:
  AZURE_FUNCTIONAPP_NAME: ic-discord
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ImagineCupDiscord.Integration\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 3.1.x
  WORKING_DIRECTORY: src/ImagineCupDiscord.Integration
  DOTNET_CORE_VERSION_INPROC: ''
jobs:
  build-and-deploy-arm:
    name: Build and Deploy ARM
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: deployment/integration.bicep
